-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GQLVsREST.Scalar exposing (Upload(..))


type Upload
    = Upload String
